### ISSUE TITLE
[Question] Looking for a UI/UX Designer?

### ISSUE THREAD

**Issue by foxnoodles** [RecaMedia/Backdoor#1]
Loving the project, if you're planning to update the you and need a designer I'd gladly contribute. Of course that is in case if you're still actively developing this project.

**Comment by RecaMedia** [comment]
Hey @foxnoodles, sorry for the long delay in my response. For some reason, I don't recall getting a notification. Anyways, I haven't done any recent updates, but I do still want to keep this project going. It's been slow since I'm always working on something else. As for UI/UX contribution, that would be great, if you're still interested. I've done all the UI within React. This project does need some TLC. I'm open to any UI suggestions. I have reconsider what features to keep and remove. Plus update it to the latest dependencies and tech.
